services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend/src/db:/app/src/db
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - 3000:5173
