services:
  database:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: ./backend/.env
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
 
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    expose:
      - 8000
    volumes:
      - ./backend/src/db:/app/src/db
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    expose:
      - 5173 
    volumes:
      - front-dist:/app/dist
        
  nginx:
    build: ./nginx
    ports: 
      - 80:80
    volumes:
      - front-dist:/app
    depends_on:
      - backend

volumes:
  front-dist:
