services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    expose:
      - 8000
    volumes:
      - ./backend/src/db:/app/src/db
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    expose:
      - 5173 
  nginx:
    build: ./nginx
    ports: 
      - 80:80
