# Generated by Django 4.1.6 on 2023-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_fieldcategory_taskscategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taskscategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
