# Generated by Django 4.1.6 on 2023-04-28 15:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_fieldcategory_name_alter_taskscategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='base_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='works.comment'),
        ),
        migrations.AlterField(
            model_name='work',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, size=None),
        ),
    ]
