# Generated by Django 4.1.6 on 2023-04-28 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0004_comment_base_comment_alter_work_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_works', to=settings.AUTH_USER_MODEL),
        ),
    ]
