# Generated by Django 4.1.6 on 2023-04-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_work_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
