# Generated by Django 4.1.6 on 2023-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_alter_work_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
