# Generated by Django 4.1.6 on 2023-04-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_work_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='field_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='works.fieldcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='tasks_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='works.taskscategory'),
            preserve_default=False,
        ),
    ]
