# Generated by Django 4.1.6 on 2023-02-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile'),
        ),
    ]
