# Generated by Django 4.1.6 on 2023-04-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_student_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
