# Generated by Django 4.1.6 on 2023-05-05 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_student_profile_studentprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teacher_profile',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='temp_passowrd',
            field=models.BooleanField(default=True),
        ),
    ]
