# Generated by Django 4.1.6 on 2023-05-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_teacher_profile_teacherprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='temp_passowrd',
            new_name='temp_password',
        ),
    ]
